export const PRICE_ALERT_CREATE_REQUEST = 'PRICE_ALERT_CREATE_REQUEST'
export const PRICE_ALERT_CREATE_SUCCESS = 'PRICE_ALERT_CREATE_SUCCESS'
export const PRICE_ALERT_CREATE_FAIL = 'PRICE_ALERT_CREATE_FAIL'
export const PRICE_ALERT_CREATE_RESET = 'PRICE_ALERT_CREATE_RESET'

export const PRICE_ALERT_LIST_REQUEST = 'PRICE_ALERT_LIST_REQUEST'
export const PRICE_ALERT_LIST_SUCCESS = 'PRICE_ALERT_LIST_SUCCESS'
export const PRICE_ALERT_LIST_FAIL = 'PRICE_ALERT_LIST_FAIL'

export const PRICE_ALERT_DELETE_REQUEST = 'PRICE_ALERT_DELETE_REQUEST'
export const PRICE_ALERT_DELETE_SUCCESS = 'PRICE_ALERT_DELETE_SUCCESS'
export const PRICE_ALERT_DELETE_FAIL = 'PRICE_ALERT_DELETE_FAIL'

export const PRICE_HISTORY_REQUEST = 'PRICE_HISTORY_REQUEST'
export const PRICE_HISTORY_SUCCESS = 'PRICE_HISTORY_SUCCESS'
export const PRICE_HISTORY_FAIL = 'PRICE_HISTORY_FAIL'

export const SMART_PRICING_REQUEST = 'SMART_PRICING_REQUEST'
export const SMART_PRICING_SUCCESS = 'SMART_PRICING_SUCCESS'
export const SMART_PRICING_FAIL = 'SMART_PRICING_FAIL'
