export const RECOMMENDATIONS_MY_REQUEST = 'RECOMMENDATIONS_MY_REQUEST'
export const RECOMMENDATIONS_MY_SUCCESS = 'RECOMMENDATIONS_MY_SUCCESS'
export const RECOMMENDATIONS_MY_FAIL = 'RECOMMENDATIONS_MY_FAIL'
export const RECOMMENDATIONS_MY_RESET = 'RECOMMENDATIONS_MY_RESET'

export const RECOMMENDATIONS_RELATED_REQUEST = 'RECOMMENDATIONS_RELATED_REQUEST'
export const RECOMMENDATIONS_RELATED_SUCCESS = 'RECOMMENDATIONS_RELATED_SUCCESS'
export const RECOMMENDATIONS_RELATED_FAIL = 'RECOMMENDATIONS_RELATED_FAIL'
export const RECOMMENDATIONS_RELATED_RESET = 'RECOMMENDATIONS_RELATED_RESET'
