# Generated by Django 5.2.9 on 2026-01-17 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_shippingadress_shippingaddress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('rec_type', models.CharField(choices=[('for_you', 'For You'), ('restock', 'Restock'), ('frequently_bought', 'Frequently Bought Together'), ('similar', 'Similar Products')], default='for_you', max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='base.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'rec_type', '-score'], name='base_recomm_user_id_ce0af6_idx')],
                'unique_together': {('user', 'product', 'rec_type')},
            },
        ),
    ]
