# Generated by Django 6.0.2 on 2026-02-05 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_productembedding_productevent_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_embedding', to='base.product')),
            ],
        ),
    ]
