# Generated by Django 6.0.2 on 2026-02-10 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_review_sentiment_review_sentiment_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='base.product')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notify_any_drop', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='base.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
